# fly.toml app configuration file generated for trip-planner-solitary-brook-0203-1512 on 2025-02-03T06:13:11Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'trip-planner-solitary-brook-0203-1512'
primary_region = 'nrt'
console_command = 'php /var/www/html/artisan tinker'

[build]
  [build.args]
    NODE_VERSION = '18'
    PHP_VERSION = '8.2'

[env]
  APP_ENV = 'production'
  LOG_CHANNEL = 'stderr'
  LOG_LEVEL = 'info'
  LOG_STDERR_FORMATTER = 'Monolog\Formatter\JsonFormatter'
  SESSION_DRIVER = 'cookie'
  SESSION_SECURE_COOKIE = 'true'
  
  APP_URL = 'https://trip-planner-solitary-brook-0203-1512.fly.dev/'
  APP_NAME = 'Trip Planner'
  APP_DEBUG = false
  DB_CONNECTION = 'pgsql'
  DB_HOST = 'aws-0-ap-northeast-1.pooler.supabase.com'
  DB_PORT = 5432
  DB_DATABASE = 'postgres'
  DB_USERNAME = 'postgres.eenuwhmjnypcmfhqbnig'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
